#ifndef _HAKO_CONFIG_HPP_
#define _HAKO_CONFIG_HPP_

#define HAKO_FIXED_STRLEN_MAX       256
#define HAKO_DATA_MAX_ASSET_NUM     4
#define HAKO_ASSET_TIMEOUT_USEC     (30 * 1000 * 1000)

#define HAKO_SHARED_MEMORY_BASE_ID   0x00FF
#define HAKO_SHARED_MEMORY_ID_0     (0x0 + HAKO_SHARED_MEMORY_BASE_ID)
#define HAKO_SHARED_MEMORY_ID_1     (0x1 + HAKO_SHARED_MEMORY_BASE_ID)

#define HAKO_LOGGER_DIRPATH             "./log/"
#define HAKO_LOGGER_FILE_PREFIX         "hako-"
#define HAKO_LOGGER_FILE_EXTENSION      ".log"
#define HAKO_LOGGER_ENTRYSIZE   256
#define HAKO_LOGGER_MAXSIZE     (1024 * 1024 * 5)
#define HAKO_LOGGER_LOGNUM      (HAKO_LOGGER_MAXSIZE / HAKO_LOGGER_ENTRYSIZE)
#define HAKO_LOGGER_ROTNUM      3

#define HAKO_PDU_CHANNEL_MAX        256

#define HAKO_CONFIG_DEFAULT_PATH "./hakoniwa_core_config.json"
#define HAKO_CONFIG_MAX_SEM     1024
#endif /* _HAKO_CONFIG_HPP_ */